server:
  port: 8081

spring:
  application:
    name: course-service

  datasource:
    url: jdbc:mysql://localhost:3306/course_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

