
server:
  port: 8083

spring:
  application:
    name: registration-service

  datasource:
    url: jdbc:mysql://localhost:3306/registration_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      StudentFeignClientgetStudentint:
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      CourseFeignClientgetCourseint:
        slidingWindowSize: 4
        minimumNumberOfCalls: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      StudentFeignClientgetStudentint:
        maxRetryAttempts: 3
        waitDuration: 1s

      CourseFeignClientgetCourseint:
        maxRetryAttempts: 3
        waitDuration: 1s

  timelimiter:
    instances:
      StudentFeignClientgetStudentint:
        timeoutDuration: 2s
        cancelRunningFuture: true

      CourseFeignClientgetCourseint:
        timeoutDuration: 2s
        cancelRunningFuture: true
        
management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG

